### ISSUE TITLE
GetFuzzyCompletions: Aborted (core dumped)

### ISSUE THREAD

**Issue by plenkl** [KeyviDev/keyvi#234]
**Describe the bug**
Program terminates abnormally when using `GetFuzzyCompletions` with a multibyte character in position 2.

**To Reproduce**
```bash
$ pip install keyvi==0.5.3
```

test.py:
```python
from keyvi.compiler import KeyOnlyDictionaryCompiler
from keyvi.dictionary import Dictionary
from keyvi.completion import PrefixCompletion

c = KeyOnlyDictionaryCompiler()
c.Add("mß")
c.Compile()
c.WriteToFile("d.kv")

d = Dictionary("d.kv")
p = PrefixCompletion(d)

p.GetFuzzyCompletions("mß", 1)
```

```bash
$ python test.py 
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Illegal UTF-8 lead byte: 159
Aborted (core dumped)
```

**Expected behavior**
Program returns without an error.

**Additional context**
I am guessing it is related to this https://github.com/KeyviDev/keyvi/blob/master/keyvi/include/keyvi/dictionary/completion/prefix_completion.h#L133

**Comment by hendrikmuhs** [comment]
This looks like a off by one error, `159 == 9f` is the 2nd byte in `ß`:

```
In [3]: "mß".encode()                                                                                                                                                                                              
Out[3]: b'm\xc3\x9f'
```

The traverser should start with `c3`.

stack trace:

```
6  0x00007f2084b62a18 in keyvi::dictionary::util::Utf8Utils::GetCharLength (utf8_lead_byte=-97 '\237') at /opt/rh/devtoolset-9/root/usr/include/c++/9/ext/new_allocator.h:89
#7  0x00007f2084b41281 in keyvi::dictionary::fsa::CodePointStateTraverser<keyvi::dictionary::fsa::StateTraverser<keyvi::dictionary::fsa::traversal::WeightedTransition> >::operator++ (this=<optimized out>)
    at /opt/rh/devtoolset-9/root/usr/include/c++/9/bits/stl_vector.h:1040
#8  0x00007f2084bcf084 in keyvi::dictionary::fsa::CodePointStateTraverser<keyvi::dictionary::fsa::StateTraverser<keyvi::dictionary::fsa::traversal::WeightedTransition> >::CodePointStateTraverser (
    this=0x7ffe1dcdbb10, f=..., state=2) at /opt/rh/devtoolset-9/root/usr/include/c++/9/bits/stl_vector.h:94
#9  0x00007f2084bcf476 in keyvi::dictionary::completion::PrefixCompletion::GetFuzzyCompletions (this=this@entry=0x2850d60, Python Exception <class 'gdb.error'> No type named class std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Rep.: 
query=, max_edit_distance=max_edit_distance@entry=1)
    at /opt/rh/devtoolset-9/root/usr/include/c++/9/bits/shared_ptr.h:129
```

I think the traverser gets initialized with the wrong buffer, somehow off by 1.

**Comment by plenkl** [comment]
Thanks @hendrikmuhs !
